version: "3.8"

services:
  webserver:
    build: .
    ports:
      - "8081:80" # Mapea puerto 8081 local al 80 del contenedor
    depends_on:
      - mysqlserver
    networks:
      - mynetwork

  mysqlserver:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
